name: Build and deploy

on:
  push:
    branches:
      - main

env:
  SPHINX_BUILDER_IMAGE: ghcr.io/wolfgangsassik/sphinx-builder:latest

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Login to ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Pull builder image
        run: docker pull ${SPHINX_BUILDER_IMAGE}
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Build html
        run: docker run --rm -u 1001 -v ./:/docs/ ${SPHINX_BUILDER_IMAGE} make html
      - name: Upload pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: _build/html/
  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
