name: Build and deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Setup Graphviz
        uses: ts-graphviz/setup-graphviz@v2
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        uses: ammaraskar/sphinx-action@master
      - name: Fix permissions
        run: |
          chmod -c -R +rX "./_build/" | while read line; do
            echo "::warning title=Invalid file permissions automatically fixed::$line"
          done
      - name: Upload pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: _build/html/
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
